name: Test
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        java: [17-jdk]
    runs-on: ubuntu-20.04
    container:
      image: openjdk:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build test --stacktrace
  buildWindowsNatives:
    runs-on: windows-2019
    steps:
      # TODO: Fix macOS in future
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build jpackage --stacktrace
        env:
          PLATFORM: "windows"
  buildMacNatives:
    runs-on: macos-12
    steps:
      # TODO: Fix macOS in future
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build jpackage --stacktrace
        env:
          PLATFORM: "macos"
      - uses: actions/upload-artifact@v3
        with:
          name: macos
          path: build